### PR TITLE
feat: adding first initial steps and initial crud

### PR DESCRIPTION
**Pull request by MorveN11**
# Pull Request

## Description

This pull request contains the creation of the initial CRUD of the clients, along with the creation of the interfaces and practices agreed with the team to have the whole development environment well defined, along with the folder order convention.
At the same time this pull request contemplates the connection of the database, the configuration of the same by means of environment variables and the realization of the sql script for its auto execution in the development environment, this already comes integrated with test data to test the correct operation of the project.

## Link To Tasks
- [Database Modeling & Connection](https://app.clickup.com/t/8689mr7ep)
- [Client Register](https://app.clickup.com/t/8689mu0j3)
- [Ci Integration](https://app.clickup.com/t/8689nghu4)
- [Own Fluent Validation](https://app.clickup.com/t/8689nxaan)

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality
      to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by JorgeHB69 — DISMISSED** [review]
I don't have any observation. Good Job.

**Comment by JeferssonCL** [comment]
@MorveN11 Please move the files from de CI configuration that is in Main branch into this PR please to follow the trainer's recommendations

**Review by JeferssonCL — DISMISSED** [review]
Good Job

**Review by JeferssonCL — APPROVED** [review]

**Review by aguirrekarina — APPROVED** [review]

**Review by Miguelito2774 — APPROVED** [review]
Good job

**Pull request merged**
