### PR TITLE
feat: Product data management (ID: CU-8689mr106)

### PR DESCRIPTION
**Pull request by JorgeHB69**
# Pull Request

Endpoints to manage product data

## Description

I provide the necessary endpoints to make crude operations with product data.
Also, I added a new type of validation (extension method) to make the correct control of the number of decimal precision that we desire to manage.
Finally, I added the validations for each property of the products and concluded with the tests for these new changes.

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality
      to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by JorgeHB69** [comment]
Task linked: [CU-8689mr106 Product Data](https://app.clickup.com/t/8689mr106)

**Review by aguirrekarina — DISMISSED** [review]

**Comment by aguirrekarina** [comment]
resolve conflicts

**Review by MorveN11 — DISMISSED** [review]
Good Job!

**Review by aguirrekarina — DISMISSED** [review]

**Review by JeferssonCL — DISMISSED** [review]

**Review by MorveN11 — APPROVED** [review]
God Job!

**Review by JeferssonCL — APPROVED** [review]
No observations

**Pull request merged**
